### ISSUE TITLE
Joining a new draft with -auth=false seems to crash the server

### ISSUE THREAD

**Issue by jpgleg** [walkingeyerobot/r38#58]
Steps to repro (might be holding one or more things wrong):

1. Create new database with updated schema for CMC/etc.
2. Create new draft with makedraft.go
3. Start server with -auth=false
4. Join draft by manually appending ?as=0 to /join/1?as=0
5. Navigate to draft 1 manually with /draft/1?as=0
6. Receive crash

I think I narrowed it down to https://github.com/walkingeyerobot/r38/blob/master/main.go#L736-L739. Commenting that out seems to stop the crashes, anyway.

**Comment by jpgleg** [comment]
```
2020/04/22 19:56:44 http: panic serving [::1]:38374: interface conversion: interface {} is nil, not string
goroutine 127 [running]:
net/http.(*conn).serve.func1(0xc0002a4280)
        /usr/lib/go-1.14/src/net/http/server.go:1772 +0x139
panic(0x998820, 0xc0002c9740)
        /usr/lib/go-1.14/src/runtime/panic.go:975 +0x3e3
main.isViewing(0xc00029ef00, 0x0, 0x1, 0x1, 0xc0002c81b0)
        /home/john/code/r38/main.go:247 +0x14f
main.ServeDraft(0xae47e0, 0xc000158620, 0xc00029ef00, 0x0)
        /home/john/code/r38/main.go:745 +0x826
main.NewHandler.func1.1(0xae47e0, 0xc000158620, 0xc00029ef00)
        /home/john/code/r38/main.go:191 +0x69
net/http.HandlerFunc.ServeHTTP(0xc00000edc0, 0xae47e0, 0xc000158620, 0xc00029ef00)
        /usr/lib/go-1.14/src/net/http/server.go:2012 +0x44
main.NonAuthMiddleware.func1(0xae47e0, 0xc000158620, 0xc00029ef00)
        /home/john/code/r38/main.go:237 +0x95
net/http.HandlerFunc.ServeHTTP(0xc00000ede0, 0xae47e0, 0xc000158620, 0xc00029ef00)
        /usr/lib/go-1.14/src/net/http/server.go:2012 +0x44
net/http.(*ServeMux).ServeHTTP(0xc000031a80, 0xae47e0, 0xc000158620, 0xc00029ef00)
        /usr/lib/go-1.14/src/net/http/server.go:2387 +0x1a5
net/http.serverHandler.ServeHTTP(0xc0001581c0, 0xae47e0, 0xc000158620, 0xc00029ef00)
        /usr/lib/go-1.14/src/net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc0002a4280, 0xae5ba0, 0xc0002c23c0)
        /usr/lib/go-1.14/src/net/http/server.go:1895 +0x86c
created by net/http.(*Server).Serve
        /usr/lib/go-1.14/src/net/http/server.go:2933 +0x35c
```

**Comment by jpgleg** [comment]
I suspect it's because we try to convert a (likely empty?) value from session.Values["userid"] to a string, gets a nil interface, and explodes.

I'm not sure I understand the middleware / fake user stuff well enough to provide a coherent fix, though.
